name: 'terminal-ai-action'
description: 'use AI to operate on your code'
inputs:
  openAiKey:
    description: 'OpenAI API Key'
    required: true
  command:
    description: 'The command to run, e.g: git diff --cached | ai -- "add tests as patch" >> tests.patch'
    required: true
runs:
  using: 'composite'
  steps:
#     - name: Setup Python
    #   uses: actions/setup-python@v5
    #   with:
    #     python-version: '3.10'  

    # - name: Install Python Dependencies
    #   run: pip install -r requirements.txt

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        registry-url: 'https://registry.npmjs.org'

    - name: Install Terminal AI
      run: npm install -g @dwmkerr/terminal-ai

    - name: Create ~/.ai/config.yaml
      run: echo "openAiKey: ${{ inputs.openAiKey }}" >> ~/.ai/config.yaml

    - name: Debug Config
      run: cat ~/.ai/config.yaml

    - name: Execute Command
      run: ${{ inputs.command }}
