name: 'Terminal AI Action'
description: 'Use Terminal AI in your workflows'
author: dwmkerr
branding:
  icon: activity
  color: blue
inputs:
  openAiKey:
    description: 'OpenAI API Key'
    required: true
  command:
    description: 'The command to run, e.g: git diff --cached | ai -- "add tests as patch" >> tests.patch'
    required: true

runs:
  using: composite
  steps:
    - name: Verify Parameters
      shell: bash
      run: |
        [[ ! -z '${{ inputs.openAiKey }}' ]] || { echo "'openAiKey' parameter is required" ; exit 1; }
        [[ ! -z '${{ inputs.command }}' ]] || { echo "'command' parameter is required" ; exit 1; }

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        registry-url: 'https://registry.npmjs.org'

    - name: Install Terminal AI
      shell: bash
      run: npm install -g @dwmkerr/terminal-ai

    - name: create ~/.ai/config.yaml
      shell: bash
      run: |
        mkdir ~/.ai
        echo "openAiKey: ${{ inputs.openAiKey }}" >> ~/.ai/config.yaml
        cat ~/.ai/config.yaml

    - name: Debug Config
      shell: bash
      run: cat ~/.ai/config.yaml

    - name: Execute Command
      shell: bash
      run: |
        ${{ inputs.command }}
        echo "Result: $?"
