name: 'Terminal AI Action'
description: 'Use Terminal AI in your workflows'
author: dwmkerr
branding:
  icon: activity
  color: blue
inputs:
  openAiApiKey:
    description: 'OpenAI API Key'
    required: true
  command:
    description: 'The command to run, e.g: git diff --cached | ai -- "add tests as patch" >> tests.patch'
    required: true

runs:
  using: composite
  steps:
    - name: Verify Parameters
      shell: bash
      run: |
        [[ ! -z '${{ inputs.openAiApiKey }}' ]] || { echo "'openAiApiKey' parameter is required" ; exit 1; }

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        registry-url: 'https://registry.npmjs.org'

    - name: Install Terminal AI
      shell: bash
      run: npm install -g @dwmkerr/terminal-ai

    - name: Install Scripts
      shell: bash
      run: |
        ln -s $(pwd)/scripts/interate-pr-commits.sh /usr/local/bin/pr-commits

    - name: Create Config File & Set API Key
      shell: bash
      run: |
        mkdir ~/.ai
        echo "openAiApiKey: ${{ inputs.openAiApiKey }}" >> ~/.ai/config.yaml

    - name: Test Command
      shell: bash
      run: |
        ${{ inputs.command }}
