name: cicd

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:

jobs:
  test:
    name: "Test: terminal-ai-action"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ai
        uses: ./
        with:
          openAiKey: "Key one"
          command: 'ai -- "hello"'
