name: Test PR - Commits Summary

on:
  push:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Iterate through Commits
        run: |
          echo "Testing base: ${{ github.event.pull_request.base.ref }}"
          # Show all of the commit logs and diffs.
          ./scripts/iterate-pr-commits.sh ${{ github.event.pull_request.base.ref }}
