name: test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/test.yml"

jobs:
  test:
    name: "Test: terminal-ai-action"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: ai
        uses: dwmkerr/terminal-ai-action@latest
        with:
          openAiKey: "Key one"
          command: 'ai -- "hello"'
