name: Test - Invalid Params

on:
  push:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Expect Fail - Invalid Parameters
        uses: ./
        with:
          WRONGopenAiKey: ${{ secrets.OPENAI_API_KEY }}
          WRONGcommand: ai "review this PR"
        continue-on-error: true
