name: Test PR - Commits Summary

on:
  # This can *only* work on a pull request, as we need to know the
  # pull request base (i.e. target branch) to compare to.
  pull_request:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Essential you fetch all of the history so we can compare each commit
          # to the base.
          fetch-depth: 0

      - name: Iterate through Commits
        uses: ./
        with:
          openAiApiKey: ${{ secrets.OPENAI_API_KEY }}
          command: |
            echo "Testing base: ${{ github.event.pull_request.base.ref }}"
            # Show all of the commit logs and diffs.
            # ./scripts/iterate-pr-commits.sh "${{ github.event.pull_request.base.ref }}" "${GITHUB_SHA}" > summary
            ai-commit-diffs "${{ github.event.pull_request.base.ref }}" "${GITHUB_SHA}" > summary

            # Summarise.
            ai 'I have provided you a git log and git diff entry for each commit in a Pull Request. Given these entries can you summarise what changes you think this pull request will merge into my branch. Summarise using Convential Commit format, with <type>: short summary\n\nDetailed info, where type is feat/fix/etc based on Conventional Commit standards' < summary
