name: Test - Basic Call

on:
  push:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Review with Terminal AI
        uses: ./
        with:
          openAiApiKey: ${{ secrets.OPENAI_API_KEY }}
          command: ai "review this PR"
