name: Test PR - Commits Summary

on:
  # This can *only* work on a pull request, as we need to know the
  # pull request base (i.e. target branch) to compare to.
  pull_request:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Iterate through Commits
        run: |
          echo "Testing base: ${{ github.event.pull_request.base.ref }}"
          # Show all of the commit logs and diffs.
          ./scripts/iterate-pr-commits.sh "${{ github.event.pull_request.base.ref }}" "${GITHUB_SHA}"
