name: Test - Invalid Params

on:
  push:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Expect Fail - Invalid Parameters
        uses: ./
        with:
          WRONGopenAiKey: apikey
          WRONGcommand: ai "review this PR"
        continue-on-error: true

      - name: Expect Fail - Invalid API Key
        uses: ./
        with:
          openAiKey: This is not vaild
          command: ai "review this PR"
        continue-on-error: true
